### ISSUE TITLE
Pretty Urls

### ISSUE THREAD

**Issue by KillWil** [tightenco/jigsaw#107]
Hello,
When compiling the build process remove 'dot'.
For example, website.com.blade.php is generated as websitecom/index.html and I would like to have something like this :  website.com/index.html
Is it possible to specify the pretty url or at least avoid the replacement of dots?
Thanks for all!

**Comment by joshmaag** [comment]
Most websites are configured to use index.html as the default page when specifying a directory. You should just be able to go to website.com/ and it will load index.html assuming that there isn't a file that take priority (like if you have index.php configured first and you have a file with that name in the directory). 

For instance, I have myproject/source/_posts/2017-04-28-generating-a-random-seed-from-a-string.blade.php and it corresponds to the url: http://localhost:8000/posts/2017-04-28-generating-a-random-seed-from-a-string/ because the index.html is found by the webserver.

**Comment by KillWil** [comment]
Thanks for your response.
I think I was not very clear previously!
I'm not dealing with the index.html file generated but with the directory...
for example a file (page) like this :
my-beautiful-blog-post.afterdot.blade.php
generate a directory without the dot and an index file, like this :
my-beautiful-blog-postafterdot/index.html
but I want (for SEO purposes)
my-beautiful-blog-post.afterdot/index.html
(the dot between "post" and "afterdot")
Thanks

**Comment by maicoqb** [comment]
Take a look on the #93. It's a PR that I create for similar reasons.

**Comment by damiani** [comment]
I'm assuming this is inside a collection? By default, if a `path` key isn't specified in `config.php` for your collection, the collection handler builds the path by looking at the filename and turning it into a slug using Laravel's `str_slug()` helper; this process removes any `.` that are in the filename. You can override this by specifying your own `path`, and returning the `filename` unchanged. 

So in `config.php`, when you define your collection, add a `path` key that returns `'{filename}'`:

```php
'collections' => [
    'my-collection' => [
        'path' => '{filename}',
    ],
],
...
``` 

That will preserve the filename with any dots, spaces, special characters, etc.
