### ISSUE TITLE
Issue when trying to test my feature with Composer's Repositories

### ISSUE THREAD

**Issue by wilburpowery** [tightenco/jigsaw#163]
Hey, I'm working on a PR, and I'm trying to use my version of the framework using Composer's VCS Repositories. But I'm not getting my fork when I do a composer update on a test install of jigsaw. 

Any idea what's wrong? 

Heres the composer.json file of the test install: 

```json{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/wilburpowery/jigsaw"
        }
    ],
    "require": {
        "tightenco/jigsaw": "^1.0"
    }
}
```

**Comment by damiani** [comment]
Make sure your version in `require` matches a branch name on your repo, and is prefixed with `dev-`. So in your case, it looks like you've posted a commit to `master`, so change the version from `^1.0` to `dev-master` and it should pull down your forked version.

Incidentally, you can link to a _local_ version of your forked code if you don't want to have to commit and push to Github constantly while in development; use `path` instead of `vcs` as the `type`, and point the `url` to the directory of the local version of your forked repo (something like `'../jigsaw'`, or whatever you name the repo when you cloned it locally, like `'../jigsaw-fork'`). Composer will symlink to your local version, and changes to the forked code will be picked up immediately by your test install. @calebporzio has a great rundown of that process on the [Tighten blog](https://tighten.co/blog/testing-laravel-framework-changes-locally-before-submitting-a-pull-request).

Sometimes, I find it necessary to nuke `composer.json` and/or `vendor` directory in order to force Composer to pick up the right codebase after making a version change in `composer.json`.

**Comment by wilburpowery** [comment]
@damiani Thanks a lot, man. I thought when pushing directly to master I could avoid specifying the branch. It's perfect now :)
