### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by robertoandres24** [tightenco/jigsaw#197]
Please update your documentation, especially in the new way of compiling with laravel mix and its different options.
I have been using jigsaw for a while and I thought it was very nice.
However, this recent change made me lose a bit of time in researching webpack docu. 
Apart from all this, excellent framework. congrats

**Comment by damiani** [comment]
Thanks @robertoandres24 for pointing that out...the branch with the Mix change was tagged prematurely. I'll be updating the docs today to reflect the change; in the meantime, there are some [notes in the PR for that feature](https://github.com/tightenco/jigsaw/pull/188) that might be helpful, which include how to switch back to Elixir/Gulp if you'd rather continue using it instead of Mix/Webpack.
