### ISSUE TITLE
Build a single page

### ISSUE THREAD

**Issue by cjf** [tightenco/jigsaw#198]
I'm using jigsaw to build a pretty big site (~3000 pages) and the process takes 5-7 minutes for a rebuild.  What I'd like to do it just be able to update/add a single page, build JUST that page, and add it to build_local/prod.  

I know this isn't currently supported, but could anyone point me towards a spot where I may be able to add in such a feature?  I know there are a lot of potential gotchas with this, but I'd like to give it a go and see if I can make it workable.

**Comment by dgursh** [comment]
5-7 minutes for every small change? Wow. 

Perhaps a solution would be for you to setup a test version of your site with a subset of pages. Then, once the code is tested on a smaller set of pages you build the entire site.

But I could see how you'd also want to just build a single page.

I would dive into the code and try tracing it. First I'd start in the Console directory and either update the Build command or make a new command called "Build Page" for example and add an option flag for the name of the markdown file?

**Comment by hellocosmin** [comment]
What I think would be really useful, is if there was the possibility to do something like
```sh
jigsaw build --collection=mycollection
```

Or, perhaps, an array of collection keys you'd define in `config.php` which, if present, would result in only those collections being built. Or, maybe a reserved key that you'd add to a collection - something like `'build' => false,`, so that the build process would skip this collection.

This way, you could set up a subset of pages in a collection, and run the build command only on that particular collection.

Would be useful for both your scenario, and if you're using collections to build individual sites (like I do 😀)

**Comment by cjf** [comment]
I was able to track down the issue on my rebuild.  It's not so much the the # of pages that is the issue.  It is the fact that I do some @include(...) that aren't small.  It causes a memory "explosion" and the system starts paging heavily.  If I make those @includes smaller, it becomes more manageable.  Still long (2-3 minutes), but manageable.

I haven't done a proper profiling yet, but it seems that whatever chunk of code is handing the @includes may be problematic.  I'm going to see if I dig in to this more, and maybe build up a test repo if I can isolate the problem.  Stay tuned.

**Comment by damiani** [comment]
The `@include` directives are handled by Laravel's Blade engine, in the `illuminate/view` dependency. It's not something we would be able to change.
