### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by jrmessias** [tightenco/jigsaw#217]
Get the following error when install jigsaw

```
Problem 1                                                                                                                       
  - Conclusion: don't install tightenco/jigsaw v1.2.1                                                                           
  - Conclusion: remove symfony/console v4.0.9                                                                                   
  - Installation request for tightenco/jigsaw ^1.2 -> satisfiable by tightenco/jigsaw[v1.2.0, v1.2.1].                          
  - Conclusion: don't install symfony/console v4.0.9                                                                            
  - tightenco/jigsaw v1.2.0 requires mnapoli/silly 1.3 - 1.5 -> satisfiable by mnapoli/silly[1.3.0, 1.3.1, 1.4.0, 1.5.0, 1.5.1].
```
I would like to use the jigsaw command on the console, so I would like to install globally.

```
My settings:
composer: 1.6.5
php: 7.2.1
tightenco/jigsaw: 1.2.1
symfony/console: 4.0.9
laravel/installer: 1.5.0
```
Any idea to resolve this?

Thanks

(sorry my English)

**Comment by damiani** [comment]
I just updated Jigsaw to remove the `mnapoli/silly` dependency which is no longer used. Give it another shot with `v1.2.2` and see if it installs for you.

That said, we don't recommend installing Jigsaw globally any more, because of the potential for conflicts with other globally-installed packages. The preferred method would be to install it local to your project. You can always add a bash alias to your system, if you want to run Jigsaw commands with `jigsaw` instead of the complete `./vendor/bin/jigsaw` command:

```
alias jigsaw='./vendor/bin/jigsaw'
```

**Comment by jrmessias** [comment]
Work!!!!! 😆 👍 🚀 

Thank you so much.
