### ISSUE TITLE
Why are assets compiled in to my `source` directory?

### ISSUE THREAD

**Issue by jameshulse** [tightenco/jigsaw#224]
From the docs:
```
By default, once your assets are compiled, they will be placed in their corresponding directories, directly under the source folder:
```
What is the reasoning behind the built assets being duplicated in `source` and also in the `build_local` folder?

Ideally I would only have the built assets residing in the `build_local` or `build_production` folders which I can ignore from git.

**Comment by hellocosmin** [comment]
This is because Webpack runs _before_ the Jigsaw `build`. 

Webpack needs an output path (`mix.setPublicPath('source/assets/')` in `webpack.mix.js`), but there's no `build_local` or `build_production` at that point in time. 

You could simply gitignore the `source/assets` directory if you don't want it in version control.

**Comment by jameshulse** [comment]
Okay I get that, thanks.

Is it possible to build the client assets outside the `source` directory? I tried the following:
```js
// webpack.mix.js

mix.setPublicPath('dist/');
```
```php
// config.php

return [
    'build' => [
        'source' => 'dist'
    ],
    ...
];
```
The build was completing but the HTML files weren't being generated. It seemed like maybe the 'source' in config.php relates to where the view assets and webpack assets are?

It feels like I need a setting like:
```
// config.php

return [
    'build' => [
        'publicPath' => 'dist'
    ]
    ...
];
```

Thanks for your help, I really like the project so far!

**Comment by hellocosmin** [comment]
The `source` key in `config.php` tells Jigsaw where your source files are located (layouts, partials, your .md files), so leave it as `'source' => 'source',`.

`publicPath` won't do anything, the key you're looking for in there is `destination`.

So with that in mind:

```php
// config.php
'build' => [
    'source' => 'source',
    'destination' => 'dist',
],
```

That would output the Jigsaw build where you want it.

But Jigsaw cleans up the destination directory when it builds, and because it runs after Webpack I think that would result in your `dist/assets` directory being removed. Haven't tested this though, try it out :)

**Comment by jameshulse** [comment]
Ah sorry, you're right, I did have `'destination' => 'dist'`. I think the problem is I don't know how to configure where jigsaw looks for assets when it runs.

What I'm trying to achieve is:

1. Webpack runs first and outputs my built JS/SASS to `/dist`
1. Jigsaw should run over the views in `source` but look for the `mix-manifest.json` in `/dist`
1. Clears `/build_local`
1. Outputs the compiled views + copies built webpack assets from `/dist` in to `/build_local`

Do you know if this configuration is possible? The reason being that I only ever want `/source` to actually contain 'source' files to prevent confusion.

**Comment by damiani** [comment]
@hellocosmin's description of why it builds assets to `source/assets` is correct; Webpack runs first to compile assets, then Jigsaw runs its build process and simply copies the compiled assets to the `build` folder.

I can't think of a way to accomplish what you're hoping, at least without some additional Webpack build step after `jigsaw build` is run. In your step `2)`, Jigsaw only parses and copies whatever files it finds in `source`.

To help prevent confusion in `/source/assets`, I typically have a `/build` directory in there that non-static assets (JS, SASS, Less files, etc.) in `/source/_assets` get built to, and I `gitignore` that `build` directory. That makes it a little clearer that the generated files in `/source/assets/build` shouldn't be edited manually. If you do that, you'll need to also update your `publicPath` in `webpack.mix.js` to:

```
mix.setPublicPath('source/assets/build');
```

...and update Mix references in your templates:

```
<link rel="stylesheet" type="text/css" href="{{ mix('css/style.css', 'assets/build') }}">
```

**Comment by jameshulse** [comment]
Thanks @damiani, that looks pretty similar to the solution I have settled on for now.
