### ISSUE TITLE
[Proposal] Custom blade directives

### ISSUE THREAD

**Issue by reed-jones** [tightenco/jigsaw#228]
[Custom blade directives](https://laravel.com/docs/5.6/blade#extending-blade) are a very useful feature in Laravel Blade. Normally these are put in the AppServiceProvider, is there a similar place in jigsaw to put custom directives?

**Comment by damiani** [comment]
Agreed, and this is already possible, though undocumented. 

Jigsaw will recognize a file named `blade.php` at the root level of your project, which allows you to return an array of Blade directives (see https://github.com/tightenco/jigsaw/issues/196#issuecomment-372735668). In addition, you can get access to the underlying BladeCompiler in order to do even more, like register custom Blade includes and components (see https://github.com/tightenco/jigsaw/pull/204).

Thanks for the reminder that I need to get this feature documented!
