### ISSUE TITLE
Suggestion: Top level config variables

### ISSUE THREAD

**Issue by raniesantos** [tightenco/jigsaw#249]
## The $page variable

Jigsaw as it is right now puts all of the config under a `$page` variable.

I suggest changing it to `$site`. My first SSG was Jekyll so it could just be me missing the old naming scheme. But while looking at my config and saying the variables out loud, I feel like a lot of it sounds/reads better as `$site->x` than `$page->x`.

### Possible way  to avoid breaking changes.

Maybe you could provide an alias. If you can add a `$site` variable that just returns what `$page` does you can avoid immediately introducing a breaking change and just add a deprecation notice about using `$page`.

## Helper functions in config

Provide a separate variable specifically for placing helpers.

Suggested names: `$helper` or `$fn`

It would keep functions out of the `$page` (or `$site`) variable which should generally contain static website details/config.

**Comment by damiani** [comment]
`$page` makes more sense to me than `$site` since the values in it—while they do include top-level `config` variables—are scoped to the individual page on which it is referenced. Per-page variables in YAML, for instance, or methods such as `$page->getPath()` and `$page->getFilename()` would make less sense when referenced under `$site`.

**Comment by raniesantos** [comment]
Fair enough, I tried.
