### ISSUE TITLE
MarkdownHandler should not replace @ symbol

### ISSUE THREAD

**Issue by Zaifor** [tightenco/jigsaw#270]
I'm not sure why the MarkdownHandler tries to escape the markdown and searches for Blade syntax. Obviously, the markdown can contain code blocks which can contain PHP, blade or different code. For example:
```
  ,,,Ruby
      "Hello, #{ @name }"
  ,,,
```

The above ends up as `"Hello, #{ {{'@'}} name }"` and throws syntax error while building. Here `@name` is instance variable in Ruby.

PHP example:

```
   ,,,PHP
      "$username@$domain"
   ,,,
```
Here we have the same problem.

Even if it's not a code block(```) the @ symbol is replaced with blade code and breakes the template.

```PHP
private function getEscapedMarkdownContent($file)
    {
        $replacements = ["<?php" => "<{{'?php'}}"];

        if (in_array($file->getFullExtension(), ['markdown', 'md', 'mdown'])) {
            $replacements = array_merge([
                // "@" => "{{'@'}}",
                // "{{" => "@{{",
                // "{!!" => "@{!!",
            ], $replacements);
        }

        return strtr($file->getContents(), $replacements);
    }
```

Is there a way to turn off `getEscapedMarkdownContent` for pure markdown files?

I'm using pure markdown files for collections and my `config.php` looks like this:
<details>
    <summary>config.php</summary>

  
     ...
      'collections' => [
      'docs' => [
        'extends' => '_layouts.doc',
        'path' => '{collection}/{filename}'
      ]
    ],
     ...

</details>

**Comment by Zaifor** [comment]
I think Blade is confused by the missing space and the first two `{{`. The getEscapedMarkdownContent returns this:

⚠️ `"#{@name}"`
```Slim
a href="#{{{@}}name }" title='Slim Homepage' Goto the Slim homepage
```
This ends up as `{@` and breakes the PHP script.

---
✅ `"#{ @name }"`
```Slim
a href="#{ {{@}}name }" title='Slim Homepage' Goto the Slim homepage
```
This works. Renders simple @ symbol.

**Comment by damiani** [comment]
What version of Jigsaw are you using? On the current release (1.2.8), these both work:

```
Hello, #{ @name }
"$username@$domain"
```
... while this throws an error:

```
Hello, #{@name}
```

This is fixed in an upcoming version that makes some changes to Jigsaw's Markdown handling, and should be released within a couple weeks. In the meantime, if you require no spaces between the `{` and the `@`, changing your file type from `.md` to `.blade.md` should fix the error.

---

The reason `@` needs to get escaped is for precisely the example you point to—you could have Blade syntax in a Markdown code block that we _don't_ want to be processed as Blade. Under the hood, Jigsaw uses the Blade compiler engine to build all of your site's files, and wraps Markdown files in a Blade wrapper for processing. If your code block were to include a Blade directive:

```
Hello, #{ @foreach }
```

... Blade would try to parse that as a typical `@foreach`, and bad things would happen. The upcoming release is a little bit smarter about what gets escaped and what does not.

**Comment by Zaifor** [comment]
Hey @damiani! Thanks for the details!

There was an "Aha!" moment after I posted the first comment. I get why the @ is escaped.

But yes I have an issue with the second one `#{@name}` without spaces. Unfortunately, I can't switch the file type. I'm using existing Git Wiki repo (only .md files) as a git submodule to build pretty docs. :) 
I will have to wait for the upcoming release.
