### ISSUE TITLE
Warning: file_put_contents error

### ISSUE THREAD

**Issue by BrandonJamesBorders** [tightenco/jigsaw#288]
- Windows 10
- Laravel Valet
- Running `npm run watch`

Probably 90% of the time when saving my scss file, the terminal returns the following:

```DONE  Compiled successfully in 141ms                                                                          16:49:48
Site built successfully!


Warning: file_put_contents(C:\Sites\my-project-name/_tmp/7444f72b9ea4096695586b124753dedb9772eabd.php): failed to open stream: No such file or directory in C:\Sites\my-project-name\vendor\illuminate\filesystem\Filesystem.php on line 122
Site built successfully!

[Browsersync] Reloading Browsers...
```

Then my browser reloads and displays:
```Warning: include(C:\Sites\my-project-name/_tmp/7444f72b9ea4096695586b124753dedb9772eabd.php): failed to open stream: No such file or directory in C:\Sites\my-project-name\vendor\illuminate\view\Engines\PhpEngine.php on line 43

Warning: include(): Failed opening 'C:\Sites\my-project-name/_tmp/7444f72b9ea4096695586b124753dedb9772eabd.php' for inclusion (include_path='.;C:\php\pear') in C:\Sites\my-project-name\vendor\illuminate\view\Engines\PhpEngine.php on line 43
```

Sometimes I can just hit save again and it'll compile without an error, sometimes I have to hit save multiple times. Either way, I have to go back to my broswer and refresh it. 

Any ideas on what is going wrong?

**Comment by BrandonJamesBorders** [comment]
I dug around for a bit to see if I could figure out what the root cause was, but a deadline dictated that I move on. Closing this issue.

**Comment by hellocosmin** [comment]
I think it’s better if you leave it open, it’s a real issue for now.

I can confirm it on Windows 10. Not using Valet, just PHP installed. And not even using Sass, I’m using PostCSS instead and it’s the same for me. 

It looks like a race condition somewhere. When it doesn’t throw a PHP warning, it usually compiles twice for me, so I get “Site built successfully!” twice. 

Only happens when saving CSS while `watch`ing files. tmp folders are set to be ignored in the Webpack config.
