### ISSUE TITLE
Remote collections HTML being cut-out

### ISSUE THREAD

**Issue by m1guelpf** [tightenco/jigsaw#307]
So right now my blog uses remote collections to pull content from a Ghost backend. This content is returned in the form of HTML (and lots of other useful properties, but HTML is the important one here).

So, when I set up my remote collections, I noticed that my content was cropped. If I had a h1 tag and then some p tags, everything after the h1 would get stripped. I traced the problem down to the Blade parser, where I gave up and decided to search for another solution.

I ended up creating a custom Parser (with another hacky workaround I may document in another issue) and manually retrieving all of the downloaded files and adding spaces between HTML tags (as that, apparently, fixes the issue).

The source is available on [this repo](https://github.com/m1guelpf/website).

I don't really know if this is an extreme edge case or something that should be fixed, just wanted to document it so others with the same problem can solve a few debugging hours. Either way, I can provide reproduction steps if needed :)

**Comment by damiani** [comment]
Hmm, I'll see if I can reproduce, and then come up with a clean solution.

**Comment by damiani** [comment]
This appears to be fixed with https://github.com/tightenco/jigsaw/pull/388 (in my testing, `<h1>The heading</h1><p>The paragraph</p>` renders correctly in a remote collection), but let me know if you are still seeing this issue when using Jigsaw v1.3.14. The 1.3.14 update requires rolling back Parsedown and ParsedownExtra to earlier versions 1.7 and 0.7, respectively.
