### ISSUE TITLE
Get current collection name

### ISSUE THREAD

**Issue by Log1x** [tightenco/jigsaw#339]
Is there currently a way to get the current pages collection name (if it's in a collection, of course)?

If not, would it be possible to add a helper? :)

Thanks

**Comment by anthonyterrell** [comment]
Hey @Log1x 👋,

> the current pages collection name (if it's in a collection, of course)? 

I'm not entirely sure how you're defining your collections, perhaps sharing what your `config.php` file looks like could help clarify?

Here's an example:

```php
// config.php
return [
    'collections' => [ 'posts' ],
];
```
[Defining Collections](https://jigsaw.tighten.co/docs/collections/) documentation.

From within your Blade files, you can do the following:

```php
<p>Total of {{ $posts->count() }} posts</p>

<ul>
@foreach ($posts as $post)
    <li>{{ $post->title }}</li>
@endforeach
</ul>
```
[Accessing Collection Items](https://jigsaw.tighten.co/docs/collections/#accessing-collection-items) documentation.

**Comment by Log1x** [comment]
Hey, thanks for the reply.

I had saw `$page->getCollection()` but it wasn't working for me but I figured out why. I was attempting to call it in my header partial in an attempt to change my padding with tailwind depending on the collection (e.g. make the header `py` smaller on `posts`) – trying it again inside of the posts partial did in fact return `posts` as expected.

That being said– is there any way to global it in a weird edge-case like this? If not, it's not an issue and I'll work around it. I tried doing a helper for it in `config.php` to see if I could maybe get around it, but it hits the same wall of failing to find the function thus failing to compile.

```php
In PageVariable.php line 20:
                                                                               
  No function named "getCollection" was found in the file "config.php"
```

**Comment by damiani** [comment]
There is, but it's not documented. The issue you're seeing is probably due to the same header partial being used on pages that _don't_ include a collection, for which the `getCollection()` method doesn't exist. `getCollection()` will throw an exception when used on non-collection pages, but the underlying collection name can also be referenced using `$page->_meta->get('collection')` which will return `null`, rather than an exception, if it is undefined. 

So something like `@if ($page->_meta->get('collection') === 'posts')` should work for your case.

**Comment by Log1x** [comment]
Perfect. Thanks!
