### ISSUE TITLE
Remote collections won't save the file in the correct folder.

### ISSUE THREAD

**Issue by wotta** [tightenco/jigsaw#340]
Hello I am running into a problem which I cannot seem to resolve.

I changed the `config.php` file so it builds a remote collection.
```php
        'posts' => [
            'items' => function() {
                $posts = json_decode(file_get_contents('http://localhost:1337/posts'));

                return collect($posts)->map(function ($post) {
                    return [
                        'extends' => '_layouts.post',
                        'section' => 'content',
                        'title' => $post->title,
                        'filename' => str_slug($post->title),
                        'content' => $post->content,
                        'date' => \Carbon\Carbon::parse($post->created_at)
                    ];
                });
            },
            'path' => 'posts/{filename}',
            'sort' => '-title'
        ],
```

Now when I run `./vendor/bin/jigsaw build local` I am getting the following error:

```bash
 View [_posts.why-i-use-laravel] not found. (View: /Users/admin/projecten/website/source/_components/post-as-rss-item.blade.php) (View: /Users/admin/projecten/website/source/_components/post-  
  as-rss-item.blade.php)
```

It did however created the file in a `_tmp` folder.
![image](https://user-images.githubusercontent.com/13332240/57546515-2e73bb00-735d-11e9-8dcb-f2b99349d532.png)

How can I fix this?

**Comment by alexmigf** [comment]
How did you fix it?

**Comment by damiani** [comment]
This is likely due to the `@include` in `source/_components/post-as-rss-item.blade.php`, which doesn't check the `_tmp` directory (used by remote collections) when building the RSS content. It has been updated in the most recent version of the blog template, but you should be able to fix it by changing line 12 of that file to:

```php
@includeFirst(['_posts.' . $entry->getFilename(), '_posts._tmp.' . $entry->getFilename()])
```

**Comment by wotta** [comment]
@damiani I actually didn't do this.
However, I cannot find how I fixed it unfortunately. If I find how I fixed it I can come back to this issue with the info.

**Comment by kresnasatya** [comment]
Hi @wotta, thanks a lot for create this issue. It really helps me to solve problem about remote collections. I was confused and take hours play around with remote collections, especially pass a data from a remote collection into a page.

My problem was how to display each data from remote collections into a page. Let say I have a page that contains list of events. Each event has a link that direct to detail event page. It takes me hours to figure out how to solve this because I don't see clear example about this from Jigsaw docs.

After I see your `config.php` snippet above, I figure out that `filename` keyword takes an important role to make a link and also `extends` keyword takes an important role to me to create a layout for detail event page. Here's my code and it works.

```php
// config.php

<?php

return [
// ...
'collections' => [
        'events' => [
            'items' => function ($config) {
                $events = require_once './data/events.php';
                return collect($events)->map(function ($event) {
                    return [
                        'extends' => '_layouts.event', // this is important
                        'title' => $event['name'],
                        'datetime' => $event['datetime'],
                        'desc' => $event['desc'],
                        'filename' => $event['slug'], // this is important
                        'location' => $event['location'],
                        'topics' => $event['topics'],
                    ];
                });
            },
        ]
    ],
]
```

```php
// sources/events.blade.php
// the getUrl() comes from page metadata by Jigsaw. Thanks to `filename` keyword from config.php
// The output will be: events/abc (e.g.)

@foreach ($events as $event)
<a href="{{ $event->getUrl() }}">{{ $event->title }}</a>
@endforeach
```

```php
// sources/_layouts/event.blade.php

// My deduction: we use $page variable because we get it from $event->getUrl() and $page variable is a reserved variable from Jigsaw.
<h1>{{ $page->title }}</h1>
```

I use Jigsaw to rebuild PHPBali community site. Here's the commit: https://github.com/phpbali-org/phpbali-org.github.io/commit/e48b3bf8a3237afa5bef3d46a0f369182ecbc63f. Feel free for anyone who have the same problem and I hope it helps. Thanks a lot.
