### ISSUE TITLE
Confused in including Hybrid files and formatting it

### ISSUE THREAD

**Issue by abrhambas01** [tightenco/jigsaw#345]
I was confused with how hybrid files usually look and how can I include/use it? 

Should I write it this way ? 

```
# This is a heading
@if (... )

@elseif 

---
> This is an emphasized text
---
//-> (Comment) or just

> this is it

@endif


````
And when I include hybrid files, will I do it like this? 
@include("hybrid.blade.md")

**Comment by damiani** [comment]
Yes, that hybrid file would work fine (though the `@elseif` will throw an error since it needs a condition). The basic thing to remember is that the hybrid file will get processed by Blade first (so all control structures like `@if`, `@foreach`, etc. as well as `{{ }}` and `$variables`, will get resolved), and _then_ a second time by the Markdown parser.

To `@include` it in another file, refer to the filename without extensions, just as you would normally for a Blade file: `@include('hybrid')` should do it.
