### ISSUE TITLE
how do you refer to the source directory

### ISSUE THREAD

**Issue by abrhambas01** [tightenco/jigsaw#349]
```php
source_path' => function($page , $section ){
        return getcwd() ."/source";
    },
```
> I added that on my config.php file in Jigsaw

***Not allowed to load local resource: file:///D:/www/jigsaw-projects/test-site/source**
But I get that in my chrome

<script src="{{ $page->source_path('assets/js/log.js') }}"></script>
 This is how I use it in my script tag in blade..

**Comment by damiani** [comment]
There's no need to specify the source directory; in fact, you shouldn't, because the Blade file in `/source`(along with `/source/assets/js/log.js`) is going to get copied to your `/build_local` or `/build_production` directory (and your JS file will end up at `build_local/assets/js/log.js`), so your paths should be relative: 

`<script src="assets/js/log.js">`
