### ISSUE TITLE
Starting from laravel app converting to Jigsaw 

### ISSUE THREAD

**Issue by adrienrobertskoove** [tightenco/jigsaw#374]
Hi !
I love the project and would like to integrate it to an existing project. 
Currently all my page are in coded with blade and pass by the normal controller view route. 
I would like to integrate jigsaw rendering to my application. But I don't know where to start. The documentation only mention how to for starting a project. 
How would I use a already working server to have some generated page and serve them as is (e.g landing page etc)?

Could I require jigsaw in the current project, and use integrated commands to generate file but use a specific controller to serve the generated pages ?

Thanks in advance for any sugestion on how to integrate jigsaw!

**Comment by stevebauman** [comment]
This would be really difficult to integrate. I think you'd have an easier time doing the opposite - starting a Jigsaw site from scratch and carrying your Laravel applications content into it, rather than the opposite.

If you begin from one of the Jigsaw starter templates you could carry your `layout.blade.php` over, then start converting each view.

**Comment by damiani** [comment]
At this point, Jigsaw is intended to be used as a standalone static site generator, not integrated into a Laravel project.
