### ISSUE TITLE
Css files are not rendering 

### ISSUE THREAD

**Issue by ithardeep** [tightenco/jigsaw#378]
The issue is, I can preview the changes locally using 'jigsaw serve' command without an issue but when I publish all files under the build_Production folder, and test using browser then CSS styles render for main index HTML page not for pages like contact/index.html.

Am I missing anything? any help will be appreciated.

**Comment by codesenpaii** [comment]
I have some experience like this, but I'm not sure if this is the same issue..
I render a classname using blade like this:

```
<a class="section-item block mb-2 p-3 rounded text-sm truncate {{ 
  $page->isActive($post->getPostUrl('id')) 
    ? 'bg-red-500 text-white hover:text-white' 
    : 'bg-gray-200 text-black hover:text-black' 
}}" href="{{ $post->getPostUrl('id') }}">
```
So it doesn't compIled on production because it was specified in blade syntax. To solve this my temporary solution was to laid out every single class name that specified in blade into some single hidden div.

```
@if ($page->production)
    <div class="hidden 
        bg-red-500 text-white hover:text-white
        bg-gray-200 text-black hover:text-black"></div>
@endif
```
So the compiler can see what the css class that used in the page.

**Comment by damiani** [comment]
@ithardeep Can you point me to a repo that includes the code for your site? It's hard to say what might be going on without seeing your code.

**Comment by ithardeep** [comment]
> I have some experience like this, but I'm not sure if this is the same issue..
> I render a classname using blade like this:
> 
> ```
> <a class="section-item block mb-2 p-3 rounded text-sm truncate {{ 
>   $page->isActive($post->getPostUrl('id')) 
>     ? 'bg-red-500 text-white hover:text-white' 
>     : 'bg-gray-200 text-black hover:text-black' 
> }}" href="{{ $post->getPostUrl('id') }}">
> ```
> 
> So it doesn't compIled on production because it was specified in blade syntax. To solve this my temporary solution was to laid out every single class name that specified in blade into some single hidden div.
> 
> ```
> @if ($page->production)
>     <div class="hidden 
>         bg-red-500 text-white hover:text-white
>         bg-gray-200 text-black hover:text-black"></div>
> @endif
> ```
> 
> So the compiler can see what the css class that used in the page.

Yeah, I did exactly, added some checks as you said and created a new config.production file and then build as production and it works

**Comment by damiani** [comment]
The way you have it setup with classes inside `{{ $page->isActive ... }}` should work just fine, so there must be something unusual going on. Are you using PurgeCSS in your `webpack.mix.js` file? After you run `npm run production`, can you inspect the CSS that gets built to `build_production` to see if the classes are missing?

**Comment by ithardeep** [comment]
> @ithardeep Can you point me to a repo that includes the code for your site? It's hard to say what might be going on without seeing your code.



> The way you have it setup with classes inside `{{ $page->isActive ... }}` should work just fine, so there must be something unusual going on. Are you using PurgeCSS in your `webpack.mix.js` file? After you run `npm run production`, can you inspect the CSS that gets built to `build_production` to see if the classes are missing?

Sorry, I don't have any public repo for it but I can show you how my master page looks like.
And it may sound absurd to you that I am not using webpack.mix.js I am using just jigsaw serve to see the changes.

Here is the code 
https://i.imgur.com/fR8alOE.png

But it strange how CSS is rendering without '/'

**Comment by damiani** [comment]
If you're using a relative path for assets, you would always want the leading `/` on there; otherwise, for non-root-level files, you'll be resolving the path relative to your current page: `href="assets/css/main.css"` would, for instance, become something like `yoursite.com/contact/assets/css/main.css` on your `contact` page. If you keep the leading `/` on there at all times, that path will always resolve to `yoursite.com/assets/css/main.css`.
