### ISSUE TITLE
Ordered/unordered lists used in markdown files not being parsed with Tailwind CSS styling

### ISSUE THREAD

**Issue by aaronduce** [tightenco/jigsaw#387]
When using an unordered list such as: 

```md
* Item
* Next Item
* Other Item
```

It is expected that it would use Tailwind list styling as documented here: https://tailwindcss.com/docs/list-style-type/#app

But instead it just displays it in text: 

```text
Item
Next Item
Other Item
```

This seems to be because when it is converting the markdown, it only produces:

```html
<ul>
  <li>Item</li>
  <li>Next Item</li>
  <li>Other Item</li>
</ul>
```

and does not apply a styling option to the ul.

**Comment by damiani** [comment]
Jigsaw doesn't provide any styling (Tailwind or otherwise) by default. And markdown never adds classes when converting to HTML, unless you were to specify them explicitly.

If you are using Tailwind (in the blog or docs template, for example) and want your unordered lists to have `list-disc` applied, you would define that in your CSS. For example:

```css
ul {
    @apply .list-disc;
}
```

**Comment by aaronduce** [comment]
Should it be applying this styling when the docs theme is selected?

**Comment by damiani** [comment]
Not automatically, no. We can add that, along with `.list-decimal` for `<ol>`, to the CSS for the blog and docs templates. 

In your existing site, though, add it to your own CSS file and you'll be good to go.
