### ISSUE TITLE
reStructuredText

### ISSUE THREAD

**Issue by cup** [tightenco/jigsaw#406]
I see that Markdown is supported:

https://jigsaw.tighten.co/docs/content-markdown

Is reStructuredText supported?

https://docutils.sourceforge.io/docs/user/rst/quickref.html

**Comment by josecanhelp** [comment]
Hey @cup. reStructuredText is not supported by Jigsaw.

Adding support for different formats increase complexities and edge cases to the point where it isn't really sustainable for a project like Jigsaw. Because of that, I don't foresee support for reStructuredText being added anytime soon.

This does open the conversation for some sort of plugin system or something that can be developed and integrated into Jigsaw, but that is something we'll need to add to the backlog for further discussion.

Thanks for the question!

**Comment by cup** [comment]
@josecanhelp FYI reStructuredText has its own release:

https://pypi.org/project/docutils

or PanDoc can be used:

https://pandoc.org
