### ISSUE TITLE
Jigsaw in a subdirectory

### ISSUE THREAD

**Issue by kaptk2** [tightenco/jigsaw#436]
I would like to have Jigsaw be in a subdirectory (http://www.example.com/~andrew) and almost everything works except for the assets. They all request from the root domain (http://www.example.com/assets/img/my-image.png) rather than the subdirectory. Is there an easy way to fix that?

**Comment by damiani** [comment]
Can you show me some code from the source file where you're referencing those assets? Are you using Laravel Mix and Webpack to build assets?

**Comment by kaptk2** [comment]
Hi @damiani I used the blog starter template (./vendor/bin/jigsaw init blog) and I made a new post that has the following yaml:
```
---
extends: _layouts.post
section: content
title: Preparing for COVID19
date: 2020-03-12
description: Resources to make sure you're prepared for remote teaching
cover_image: /assets/img/my-image.png
featured: true
categories: [covid]
---
```
I also get the same type of errors when trying to pull in the search assets. A request to /index.json and the /assets/img/magnifying-glass.svg both fail because they go for the root domain and not the sub folder.

I am using Mix and Webpack to build the assets and almost nothing from the blog quickstart has been changed.

**Comment by damiani** [comment]
First, I would update `baseUrl` in `config.php` to include your subdomain, so that it gets included whenever Jigsaw tries to build an absolute path:

```php
return [
    'baseUrl' => 'https://www.example.com/~andrew',
    ...
```

Then, you can update the `post.blade.php` template, which references `cover_image` on line 12, to include the `baseUrl`:

```html
<img src="{{ $page->baseUrl }}{{ $page->cover_image }}" alt="{{ $page->title }} cover image" class="mb-2">
```

For the search Vue component, you can find the references to `index.json` and `magnifying-glass.svg` in the `Search.vue` component. Add your subdirectory there (in 3 places), and then rebuild your assets with `npm run production`:

```js
<img src="~andrew/assets/img/magnifying-glass.svg" alt="search icon" class="h-4 w-4 max-w-none">

...

axios('~andrew/index.json').then(response => {

...

input[name='search'] {
    background-image: url('~andrew/assets/img/magnifying-glass.svg');

```
 
There are a couple other changes you'll want to make: in `master.blade.php`, or anywhere you are using the `mix` helper, you'll probably need to add your subdirectory there:

```html
<link rel="stylesheet" href="{{ mix('css/main.css', '~andrew/assets/build') }}">

...

<script src="{{ mix('js/main.js', '~andrew/assets/build') }}"></script>
```

**Comment by kaptk2** [comment]
That almost worked when I run npm run production I get this error:

This dependency was not found:
* andrew/assets/img/magnifying-glass.svg ...

Also this breaks it so that I can no longer work locally on the site. Is there a way to have that work as well?

**Comment by ryangjchandler** [comment]
Place the production url inside of the production config file.

config.production.php

```php
<?php

return [
    'base_url' => 'https://www.example.com/~andrew',
];
```

and the in the regular config.php file, use your local test domain / `yarn watch`.
