### ISSUE TITLE
[Proposal] Include way to handle 404 pages

### ISSUE THREAD

**Issue by underparnv** [tightenco/jigsaw#60]
Not sure if I'm just overlooking the section in the documentation or through my trials through the code, but would be cool to handle missing pages with a `404.blade.php` file or something when those errors occur.

Was thinking along the lines of how [Laravel uses the errors folder](https://github.com/laravel/laravel/tree/master/resources/views/errors) for those views, though not entirely certain how to implement it yet at this point.

**Comment by adamwathan** [comment]
Hey David! I wish this was that easy, but since it's a static site it has to be handled at the webserver level. If you use GitHub Pages, you can just create a `404.html` file in your root and it will work automatically, otherwise have to configure it in the webserver, and point whatever errors you want to whatever error pages 👍

**Comment by underparnv** [comment]
Duh. Was way over thinking this one. Thanks!

**Comment by chrisvidal** [comment]
Hi i tried ot crate a 404.html in the source folder, but it is not copy over during the build process. Any idea on how to copy this file ?
thanks

**Comment by adamwathan** [comment]
I think that's probably an issue of pretty URLs being enabled by default so your file is ending up at /build_github/404/index.html

Might be a way to disable that per page if you're clever 🤔

**Comment by damiani** [comment]
@chrisvidal Make sure that `.copy` line in your gulpfile falls after the `.exec` line, or else the file that gulp just copied will get deleted at the `.exec` step. Otherwise, using `.copy` as you have it should work. 

One thing you might change is to append a `_` before the filename in `source`, if you don't need end up with a `404/index.html` file in `build_github`:

```
.copy( elixir.config.publicPath + '/_404.html', 'build_github/404.html')
```

**Comment by chrisvidal** [comment]
thank @damiani 
yes I did this, but the file is not copied neither

**Comment by damiani** [comment]
Another way you can do it, if you have pretty URLs enabled, is to name your `source` file `404.html.blade.php`. Jigsaw will process it as a normal Blade file (allowing you to use a parent template, for example, just like with any Jigsaw file) and output it to `build_github/404.html/index.html`, which will be accessible in the browser at `404.html`.

**Comment by chrisvidal** [comment]
Interesting idea, I am using github pages, let's see if it can support this
