### ISSUE TITLE
Blog Posts

### ISSUE THREAD

**Issue by lukashl** [tightenco/jigsaw#73]
Is in jigsaw possible create a blog post?

**Comment by iign** [comment]
Jigsaw is a static generator, you can create a folder structure for a blog pretty easily:

/source/blog/
/source/blog/post-title.blade.php

And probably:

/_layouts/posts.blade.php
/_layouts/post-detail.blade.php

**Comment by marcusmoore** [comment]
I think we might be waiting for a new release to be tagged with the [collection features](https://github.com/tightenco/jigsaw/pull/71) included?

**Comment by iign** [comment]
Oh! Just saw that. Yup, that's probably it.

**Comment by damiani** [comment]
Yes, the collection features are undergoing some final syntax changes and will be tagged as a release this week. That release will support blogging and a variety of other collection-type uses.

**Comment by marcusmoore** [comment]
Really looking forward to that @damiani. Thank you!

**Comment by marcusmoore** [comment]
Hello @damiani any chance you can publish the work-in-progress branch? I would appreciate it. Thanks for your work!

**Comment by erickpatrick** [comment]
BTW, if you want to use the current state of the collection feature, you can just add `dev-master` into you `composer.json` file instead of the version number. And, of course, after that, `composer update` (or `composer install` if from scratch). That's how I'm using for one project I'm currently working on.

However, be aware that it won't be safe to `composer update` after that if the next PR that's going to be merged breaks compatibility with the current state of the `master` branch

**Comment by damiani** [comment]
> However, be aware that it won't be safe to `composer update` after that if the next PR that's going to be merged breaks compatibility with the current state of the master branch

...which it does, but in ways that won't be terribly difficult to fix. We'll post a migration guide, as well, which details the breaking changes.

**Comment by erickpatrick** [comment]
Awesome, if you need any help with that (migration guide) or something else, let me know =)

**Comment by lukashl** [comment]
So, what about new relase ? It is now publish ?

**Comment by damiani** [comment]
Collections support is now in v1.0.0; here are some [instructions for upgrading an existing site](http://jigsaw.tighten.co/docs/upgrading/) if you used an earlier (pre-v1) version of collections.
